package net.pettip.app.navi.ui.theme
import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF6750A4)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFFFFFFF)
val md_theme_light_onPrimaryContainer = Color(0xFF22005D)
val md_theme_light_secondary = Color(0xFF625B71)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFE8DEF8)
val md_theme_light_onSecondaryContainer = Color(0xFF1E192B)
val md_theme_light_tertiary = Color(0xFF7E5260)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFFFD9E3)
val md_theme_light_onTertiaryContainer = Color(0xFF31101D)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFFFBFF)
val md_theme_light_onBackground = Color(0xFF1C1B1E)
val md_theme_light_surface = Color(0xFFFFFBFF)
val md_theme_light_onSurface = Color(0xFF1C1B1E)
val md_theme_light_surfaceVariant = Color(0xFFE7E0EB)
val md_theme_light_onSurfaceVariant = Color(0xFF49454E)
val md_theme_light_outline = Color(0xFF7A757F)
val md_theme_light_inverseOnSurface = Color(0xFFF4EFF4)
val md_theme_light_inverseSurface = Color(0xFF313033)
val md_theme_light_inversePrimary = Color(0xFFCFBCFF)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF6750A4)
val md_theme_light_outlineVariant = Color(0xFFCAC4CF)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFFCFBCFF)
val md_theme_dark_onPrimary = Color(0xFF381E72)
val md_theme_dark_primaryContainer = Color(0xFF4F378A)
val md_theme_dark_onPrimaryContainer = Color(0xFFE9DDFF)
val md_theme_dark_secondary = Color(0xFFCBC2DB)
val md_theme_dark_onSecondary = Color(0xFF332D41)
val md_theme_dark_secondaryContainer = Color(0xFF4A4458)
val md_theme_dark_onSecondaryContainer = Color(0xFFE8DEF8)
val md_theme_dark_tertiary = Color(0xFFEFB8C8)
val md_theme_dark_onTertiary = Color(0xFF4A2532)
val md_theme_dark_tertiaryContainer = Color(0xFF633B48)
val md_theme_dark_onTertiaryContainer = Color(0xFFFFD9E3)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF1C1B1E)
val md_theme_dark_onBackground = Color(0xFFE6E1E6)
val md_theme_dark_surface = Color(0xFF1C1B1E)
val md_theme_dark_onSurface = Color(0xFFE6E1E6)
val md_theme_dark_surfaceVariant = Color(0xFF49454E)
val md_theme_dark_onSurfaceVariant = Color(0xFFCAC4CF)
val md_theme_dark_outline = Color(0xFF948F99)
val md_theme_dark_inverseOnSurface = Color(0xFF1C1B1E)
val md_theme_dark_inverseSurface = Color(0xFFE6E1E6)
val md_theme_dark_inversePrimary = Color(0xFF6750A4)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFFCFBCFF)
val md_theme_dark_outlineVariant = Color(0xFF49454E)
val md_theme_dark_scrim = Color(0xFF000000)

//---------------------------------------------------------------------------//
// 디자인팀 색상

val design_intro_bg = Color(0xFF4783F5)
val design_login_bg = Color(0xFFF6F8FC)
val design_placeHolder = Color(0xFFB5B9BE)
val design_textFieldOutLine = Color(0xFFE3E9F2)
val design_button_bg = Color(0xFF4783F5)
val design_login_text = Color(0xFF222222)
val design_login_kakaobtn = Color(0xFFF6E24B)
val design_login_naverbtn = Color(0xFF03CF5D)
val design_login_facebookbtn = Color(0xFF1877F2)
val design_btn_border = Color(0xFF333333)
val design_sharp = Color(0xFFF54F68)
val design_shadow = Color(0x264E6085)
val design_skip = Color(0xFF737980)
val design_camera_bg = Color(0xFF5E6D7B)
val design_select_btn_text = Color(0xFF4783F5)
val design_select_btn_bg = Color(0xFFF6F8FC)
val design_select_btn_border = Color(0xFF4783F5)
val design_bottomnav_text = Color(0xFF8C949C)
val design_weather_1 = Color(0xFF3AA5FF)
val design_weather_2 = Color(0xFF2DCC66)
val design_weather_3 = Color(0xFFFDA50E)
val design_weather_4 = Color(0xFFF94B65)
val design_home_bg = Color(0xFFF6F8FC)
val design_icon_bg = Color(0xFFF1F4FB)
val design_icon_5E6D7B = Color(0xFF5E6D7B)
val design_icon_time_bg = Color(0xFFFFDBDB)
val design_icon_distance_bg = Color(0xFFCBE4FF)
val design_grad_end = Color(0xFF545454)
val design_white = Color(0xFFFFFFFF)
val design_deep_blue = Color(0xFF2B60C4)
val design_DDDDDD = Color(0xFFDDDDDD)
val design_C3D3EC = Color(0xFFC3D3EC)
val design_76A1EF = Color(0xFF76A1EF)
val design_alpha50_black = Color(0x80000000)
val design_alpha60_black = Color(0x99000000)
val design_f1f1f1 = Color(0xFFF1F1F1)
val design_B5B9BE = Color(0xFFB5B9BE)
val design_EFECFE = Color(0xFFEFECFE)
val design_EEEEEE = Color(0xFFEEEEEE)
val design_999999 = Color(0xFF999999)
val design_FCE9B3 = Color(0xFFFCE9B3)
val design_CBE8F3 = Color(0xFFCBE8F3)
val design_dark = Color(0xFF000000)
val design_ = Color(0x00000000)


//---------------------------------------------------------------------------//


val seed = Color(0xFF6750A4)
val CustomColor1 = Color(0xFFF5AAB5)
val light_CustomColor1 = Color(0xFF9B4053)
val light_onCustomColor1 = Color(0xFFFFFFFF)
val light_CustomColor1Container = Color(0xFFFFD9DD)
val light_onCustomColor1Container = Color(0xFF400014)
val dark_CustomColor1 = Color(0xFFFFB2BD)
val dark_onCustomColor1 = Color(0xFF5F1127)
val dark_CustomColor1Container = Color(0xFF7D293C)
val dark_onCustomColor1Container = Color(0xFFFFD9DD)
